name: huggle
version: "3.2.1"
summary: Diff browser for MediaWiki based websites intended to deal with vandalism
description: Diff browser for MediaWiki based websites intended to deal with vandalism
confinement: strict
epoch: 0
grade: stable

apps:
  huggle:
    command: desktop-launch huggle
    plugs:
        - unity7
        - x11
        - network
        - home
        - opengl
        - pulseaudio
        - browser-support

parts:
  application:
#   prepare: ./build/prepare_snap.sh
    plugin: cmake
    configflags:
      - -DQT5_BUILD=true
      - -DLINUX_SNAP=true
      - -DHUGGLE_EXT=true
    source-type: git
    source: https://github.com/huggle/huggle3-qt-lx
    source-subdir: huggle
    stage-packages:
      - libqt5gui5
      - libqt5webkit5
      - libqt5concurrent5
      - libqt5network5
      - libqt5multimediaquick-p5
      - libqt5multimediawidgets5
    build-packages:
      - qtmultimedia5-dev
      - libqt5webkit5-dev
    after: [desktop-qt5]
